import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
// import './globals.css';
import ReactQueryProvider from "../providers/ReactQueryProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
import Header from "@/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <ThemeProvider theme={theme}>
              <div style={{margin: "5px"}}>
               <Link href='https://www.nasa.gov/' style={{textDecoration: "none"}}>NASA.Data</Link> 
               <Header />
                {children}
              </div>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
